CREATE DATABASE SIVAR_BURGUERS;
GO
USE SIVAR_BURGUERS;
GO


CREATE TABLE Usuario
(
    idUsuario INT NOT NULL IDENTITY,
    Contraseña VARCHAR (50) NOT NULL,
    Nombre_Empleado VARCHAR (100) NOT NULL,
    Telefono VARCHAR(9),
	Rol VARCHAR(25),
    CONSTRAINT PK_USUARIO PRIMARY KEY(idUsuario)
);

CREATE TABLE Mesa
(
    idMesa INT NOT NULL IDENTITY,
    Numero_Mesa INT NOT NULL,
    CONSTRAINT PK_MESA PRIMARY KEY(idMesa)
);

CREATE TABLE Pago
(
    idPago INT NOT NULL IDENTITY,
    Tipo_Pago VARCHAR (20) NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY(idPago)
);

CREATE TABLE Estado_Pedido
(
    idEstado_Pedido INT NOT NULL IDENTITY,
    Tipo_Estado VARCHAR(30),
    CONSTRAINT PK_ESTADO_PEDIDO PRIMARY KEY(idEstado_Pedido)
);

CREATE TABLE Categoria
(
    idCategoria INT NOT NULL IDENTITY,
    Nombre_Categoria VARCHAR (100) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY(idCategoria)
);

CREATE TABLE Platillo
(
    idPlatillo INT NOT NULL IDENTITY,
    Nombre_Platillo VARCHAR (120),
    Precio DECIMAL (10,2),
    Descripcion VARCHAR (255),
	idCategoria INT NULL,
    CONSTRAINT PK_PLATILLO PRIMARY KEY(idPlatillo)
);

CREATE TABLE Cliente
(
    idCliente INT NOT NULL IDENTITY,
    Nombre VARCHAR (40) NOT NULL,
    Apellido VARCHAR (50) NULL,
	idPedido INT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(idCliente)
);

CREATE TABLE Pedido
(
    idPedido INT NOT NULL,
    idUsuario INT NULL,
    idCliente INT NULL,
    idMesa INT NULL,
    idEstado_Pedido INT NULL,
    FECHA DATE,
    HORA TIME,
	idPago INT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY(idPedido)
);

CREATE TABLE Detalle_Pedido
(
    idDetalle_Pedido INT NOT NULL IDENTITY,
    idPlatillo INT NULL,
    idPedido INT NULL,
    Cantidad INT,
    SubTotal DECIMAL (10,2),
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY(idDetalle_Pedido)
);

--Llaves Foraneas


--Tabla Platillo 
ALTER TABLE Platillo
ADD CONSTRAINT FK_CATEGORIA_PLATILLO FOREIGN KEY (idCategoria) REFERENCES Categoria(idCategoria) ON UPDATE CASCADE ON DELETE CASCADE;
GO
--Tabla Pedido
ALTER TABLE Pedido
ADD CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario) ON UPDATE CASCADE ON DELETE CASCADE;
GO
ALTER TABLE Pedido
ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (idCliente) REFERENCES Cliente(idCliente) ON UPDATE CASCADE ON DELETE CASCADE;
GO
ALTER TABLE Pedido
ADD CONSTRAINT FK_PEDIDO_MESA FOREIGN KEY (idMesa) REFERENCES Mesa(idMesa) ON UPDATE CASCADE ON DELETE CASCADE;
GO
ALTER TABLE Pedido
ADD CONSTRAINT FK_PEDIDO_ESTADO FOREIGN KEY (idEstado_Pedido) REFERENCES Estado_Pedido(idEstado_Pedido) ON UPDATE CASCADE ON DELETE CASCADE;
GO
ALTER TABLE Pedido
ADD CONSTRAINT FK_PEDIDO_PAGO FOREIGN KEY (idPago) REFERENCES Pago(idPago) ON UPDATE CASCADE ON DELETE CASCADE;
--Tabla Cliente
ALTER TABLE Cliente
ADD CONSTRAINT FK_CLIENTE_PEDIDO FOREIGN KEY (idPedido) REFERENCES Pedido(idPedido) ON UPDATE NO ACTION ON DELETE NO ACTION
GO
--Tabla Detalle Pedido
ALTER TABLE Detalle_Pedido
ADD CONSTRAINT FK_DETALLE_PEDIDO_PLATILLO FOREIGN KEY (idPlatillo) REFERENCES Platillo(idPlatillo) ON UPDATE CASCADE ON DELETE CASCADE;
GO
ALTER TABLE Detalle_Pedido
ADD CONSTRAINT FK_DETALLE_PEDIDO_PEDIDOS FOREIGN KEY (idPedido) REFERENCES Pedido(idPedido) ON UPDATE CASCADE ON DELETE CASCADE;
GO


--INSERTAR DATOS
--PAGO
INSERT INTO Pago VALUES ('Credito'),('Paypal'),('Efectivo');
--CATEGORIA
INSERT INTO Categoria VALUES ('Hamburguesas Picantes');
--USUARIO
INSERT INTO Usuario VALUES ('','','','')
UPDATE Usuario SET Contraseña = '',Nombre_Empleado = '',Telefono = '',Rol = '' WHERE idUsuario = 

CREATE VIEW v_platillo
AS
SELECT p.idPlatillo,p.Nombre_Platillo,p.Precio,p.Descripcion,c.Nombre_Categoria FROM Platillo p
INNER JOIN Categoria c ON p.idCategoria = c.idCategoria